('2015-01-17 10:35:08.780858', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:10.187837', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:11.724083', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:13.259797', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:14.795830', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:16.332111', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:17.739863', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:19.275854', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:20.683842', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:22.219805', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:23.755768', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:25.291882', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:26.827836', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:28.235826', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:29.771834', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:31.181341', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:31.181832', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:32.715809', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:32.716064', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:34.251915', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:34.252229', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:35.787858', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:35.788153', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:37.323734', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:37.324100', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:38.731827', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:40.267803', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:41.675764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:43.211982', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:44.747790', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:44.748028', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:46.284163', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:46.285033', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:47.820022', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:49.227743', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:50.763893', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:52.171850', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:53.707868', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:55.243764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:56.780095', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:58.315857', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:35:59.723882', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:01.259898', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:02.667939', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:04.203789', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:05.739742', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:07.275844', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:07.276156', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:08.811856', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:08.812127', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:10.219847', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:10.220284', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:11.755916', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:11.756270', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:13.291892', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:13.292166', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:14.699692', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:16.235801', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:17.771821', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:19.308122', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:19.308543', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:20.715792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:20.716215', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:22.251817', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:23.787758', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:25.195747', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:26.731796', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:28.267690', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:29.803854', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:31.211783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:32.747827', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:34.283807', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:35.692014', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:37.228153', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:38.763796', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:40.299790', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:41.835983', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:43.243991', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:44.779802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:44.780043', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:46.187783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:46.188055', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:47.723758', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:47.724037', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:49.259806', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:50.795812', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:36:52.331791', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:03.493115', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:03.498214', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:05.771808', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:07.179902', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:07.425379', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:07.872959', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:08.239307', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:08.249045', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:08.335887', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:08.672047', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:08.715791', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:08.843472', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:10.063658', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:10.251839', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:11.015704', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:11.327752', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:11.328115', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:11.787820', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:13.323777', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:13.662009', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:13.662349', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:13.722358', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:13.725913', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:14.406677', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:14.731816', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:16.267804', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:18.894777', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:18.895194', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:19.104675', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:19.211710', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:19.211999', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:19.623876', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:19.794699', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:20.116138', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:22.283858', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:22.284194', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:23.922234', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:25.228037', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:25.228450', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:26.654625', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:37:28.171751', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:31.243791', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:34.315844', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:37.259795', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:38.667758', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:40.203785', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:41.739823', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:43.275999', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:44.811770', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:46.219799', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:47.755785', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:49.291756', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:50.699735', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:52.235865', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:53.771805', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:55.307815', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:55.308336', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:56.715859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:56.716307', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:58.251829', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:58.252216', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:59.787853', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:37:59.788115', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:01.195758', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:01.196099', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:02.731852', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:04.267794', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:05.803856', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:07.211908', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:07.212462', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:08.747875', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:08.748133', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:10.283845', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:10.284160', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:11.691834', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:14.763732', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:16.299802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:17.835804', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:19.243780', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:20.780004', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:22.188085', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:23.723731', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:25.259751', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:26.795783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:28.332076', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:29.739764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:31.275802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:31.276054', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:32.683840', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:32.684238', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:34.219817', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:34.220215', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:35.755794', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:35.756255', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:37.291789', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:38.827784', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:40.235790', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:41.771772', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:43.179812', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:43.180245', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:44.715787', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:44.716212', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:46.251859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:47.279184', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:47.285739', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:49.166874', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:49.193822', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:49.323745', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:50.154884', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:52.267792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:53.675754', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:55.211737', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:55.324257', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:38:56.747761', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:58.283811', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:38:59.819765', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:01.227759', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:02.763817', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:04.171936', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:05.707941', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:07.244358', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:07.810565', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:39:08.779820', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:08.780103', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:10.315817', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:10.316106', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:14.667823', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:17.739835', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:20.811859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:20.812301', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:23.755790', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:26.699793', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:29.772018', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:31.307818', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:32.715828', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:34.251831', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:35.787715', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:37.195806', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:38.732772', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:40.267682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:41.803814', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:43.211741', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:43.211982', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:46.283842', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:46.284110', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:49.227999', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:49.228435', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:52.299792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:55.243865', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:58.187861', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:39:58.188377', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:01.259891', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:02.795806', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:04.331845', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:05.739715', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:07.275825', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:08.683783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:10.219864', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:11.755895', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:13.291805', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:14.827808', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:16.235702', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:17.771792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:19.179856', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:19.180358', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:20.715767', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:20.716201', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:22.042690', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:40:22.251767', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:22.252179', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:23.787819', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:23.788137', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:25.323849', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:25.324151', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:26.330416', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:40:26.553824', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:40:26.605954', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:40:26.628855', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-01-17 10:40:26.731654', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:28.267823', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:29.675791', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:31.211987', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:31.212277', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:32.747823', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:32.748136', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:34.283973', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:34.284502', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:35.819750', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:38.763779', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:40.171802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:41.707752', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:43.243914', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:44.779818', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:46.315775', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:47.723794', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:49.259768', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:50.667743', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:52.203784', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:53.739749', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:55.275735', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:56.811704', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:58.219888', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:58.220242', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:59.755798', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:40:59.756061', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:01.291853', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:02.699830', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:04.235771', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:05.771825', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:08.715881', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:08.716368', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:11.787709', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:14.731791', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:16.267748', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:17.803751', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:19.211977', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:20.747848', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:22.283816', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:23.691777', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:25.227777', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 10:41:57.229915', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:41:58.766151', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:42:10.554464', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:42:13.101514', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 10:42:14.125889', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:39.225650', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:48.196852', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:49.217304', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:50.496903', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:55.216985', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:55.613380', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:29:57.209795', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:30:02.428999', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-01-17 11:30:13.228029', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:14.763891', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:16.171836', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:17.707812', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:19.243949', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:20.779769', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:22.315835', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:31.275828', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:47.787781', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-01-17 11:30:50.731795', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
