('2015-04-18 10:09:22.244868', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:23.779516', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:25.315607', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:26.723672', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:28.259692', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:29.795640', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:31.203572', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:09:32.739647', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:38.787596', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:40.323631', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:41.731640', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:43.267718', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:44.675572', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:46.211583', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:47.747764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:49.283745', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:50.819602', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:52.227711', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:53.763792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:55.171676', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:56.707591', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:58.243607', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:34:59.779754', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:01.315640', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:02.723575', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:04.259568', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:05.795599', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:07.203718', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:08.739671', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:10.275624', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:11.811684', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:13.219497', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:14.755548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:16.291697', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:17.699600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:19.235600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:20.771657', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:22.307632', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:23.715676', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:25.251661', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:26.787630', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:28.195658', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:29.731651', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:31.267591', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:32.803743', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:34.339602', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:35.747543', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:37.283653', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:38.691545', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:40.227538', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:41.763520', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:43.299628', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:44.835494', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:46.243549', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:47.779540', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:49.187532', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:50.723504', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:52.259632', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:53.795521', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:55.331505', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:55.331961', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:56.739550', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:58.275579', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:59.683536', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:01.219778', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:02.755641', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:04.291540', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:05.827637', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:07.235571', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:08.771577', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:10.179549', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:11.715609', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:13.251669', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:14.787614', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:16.323566', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:17.731736', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:19.267766', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:20.675687', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:22.211654', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:23.747676', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:25.283717', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:26.819682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:28.227549', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:29.763650', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:31.299580', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:32.707638', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:34.243518', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:35.779448', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:37.315628', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:38.723597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:40.259610', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:41.667657', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:43.203505', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:44.739687', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:46.275582', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:47.811669', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:49.219597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:50.755495', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:52.291728', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:49.251747', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:50.787645', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:52.195718', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:53.731571', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:55.267648', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:56.803671', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:58.339775', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:59.747496', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:01.283626', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:02.691534', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:04.227702', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:05.763469', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:07.299544', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:08.835667', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:10.243608', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:11.779627', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:11.780082', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:13.187729', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:13.621101', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:30:14.723590', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:14.723987', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:16.259608', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:16.259984', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:17.795486', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:19.331606', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:19.332060', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:20.739608', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:20.740007', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:22.275699', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:23.683665', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:25.219683', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:26.755687', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:28.291600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:29.827802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:31.235588', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:32.771703', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:34.179697', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:35.715612', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:37.251588', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:38.787603', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:40.323615', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:41.731659', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:43.267569', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:46.211579', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:47.747631', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:49.283611', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:52.227543', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:53.763641', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:56.707602', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:58.243698', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:59.779666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
