('2015-02-07 10:33:46.570830', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:46.571704', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:46.642053', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:46.773929', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:47.045929', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:47.182020', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:48.045145', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:48.542072', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:48.685569', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:49.086040', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:49.549412', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:50.590016', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:51.053634', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:57.036929', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:28.044927', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:28.093407', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:30.669595', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:31.534048', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:34.541834', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:35.181649', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:35.534089', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:37.277968', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:38.158036', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:55.243949', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:34:56.779916', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:10.219663', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:11.755597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:13.291924', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:14.699849', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:16.235911', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:17.771852', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:20.715613', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:23.787913', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:24.173814', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:25.195850', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:35.691621', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:37.227642', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:49.259838', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:58.219759', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:59.755859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:01.291538', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:05.771869', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:13.323842', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:19.211885', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:20.493145', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:36:20.493709', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:36:20.747585', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:22.283694', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:23.819847', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:25.227774', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:26.763668', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:28.171873', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:29.708302', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:35.723883', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:37.259574', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:40.921327', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:36:48.373417', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:36:48.374193', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:36:50.699794', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:52.236112', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:52.237019', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:53.771989', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:53.772600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:55.307623', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:02.731958', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:05.096312', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:07.211937', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:08.747830', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:10.283849', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:11.691612', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:12.164551', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:12.204604', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:13.227863', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:16.514727', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:17.835696', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:19.224285', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:19.243438', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:20.779603', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:20.779877', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:22.187531', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:23.723857', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:25.259761', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:29.739932', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:32.683819', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.755908', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.756847', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.291607', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.292086', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:38.827905', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:38.828710', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.235871', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.236389', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:41.771912', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:41.772460', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:43.179584', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:43.179859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:44.715920', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:46.251555', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:47.787600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:49.323899', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:49.324463', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:50.731898', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:50.732413', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:52.267867', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:53.675785', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:55.211864', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:56.747513', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:58.283816', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:01.227603', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:02.763789', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:04.171630', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:05.707923', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:05.708787', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:07.243574', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:07.243867', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:08.779886', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:08.780475', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:10.316520', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:10.317291', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:11.723858', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:13.259802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:17.739687', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:19.275838', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:20.811598', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:22.219649', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:32.715981', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:34.251820', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:35.787992', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:35.788508', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:37.195939', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:37.196867', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:38.731827', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:38.732368', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:40.267591', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:40.268000', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:41.571306', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:41.803956', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:41.804476', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:43.339524', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:44.747735', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:46.283826', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:47.691842', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:48.591673', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:48.595670', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:49.227597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:49.227876', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:50.763833', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.299800', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.664544', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:53.023401', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:53.031637', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:53.835872', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:55.243813', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:56.779836', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:58.187828', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:58.565298', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:58.932966', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:59.723834', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:04.331893', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:05.442759', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:05.483658', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:05.549101', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:05.739793', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:05.869039', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:06.352677', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:07.275962', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:08.683632', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:10.219955', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:11.755838', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:12.744212', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:13.291879', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:14.827856', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:15.595768', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:18.453753', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:18.455504', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:20.715811', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:28.267820', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:31.211999', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:32.747846', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:34.283913', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:35.819888', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:37.227966', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:38.763937', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:40.171579', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:40.171899', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:41.707871', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:41.708407', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:43.243778', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:43.244562', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:44.779946', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:44.780542', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:46.315599', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:46.316039', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:47.723931', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:47.724563', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:49.259876', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:50.667764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:52.203837', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:53.739764', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:55.275958', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:56.811902', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:56.812449', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:58.219884', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:59.755819', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:11.787597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:11.787930', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:13.196050', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:13.196605', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:14.731856', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:14.732457', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:16.267916', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:16.268505', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:17.803813', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:19.339688', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:19.339955', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:20.747819', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:20.748320', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:22.283874', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:22.284376', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:23.691986', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:23.692852', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:25.227862', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:26.763835', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:28.299937', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:28.300771', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:29.835918', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:31.243918', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:32.779942', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:34.187943', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:34.430425', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:40:34.882132', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:40:35.723882', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:37.091384', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:40:37.259513', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:38.795951', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:43.275869', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:44.683904', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:44.684679', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:46.219927', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:46.220527', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:47.756104', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:47.756886', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:49.291597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:49.291932', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:49.292985', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:40:52.235827', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:55.179807', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:59.787848', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:02.731634', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:08.747851', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:13.202837', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:13.213095', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:13.307004', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:13.554559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:13.554974', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:19.243882', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:20.779916', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:22.315844', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:22.316436', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:23.723850', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:23.724450', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:25.259644', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:25.259961', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:26.795881', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:26.796444', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:28.203919', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:28.204475', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:32.812348', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:53.803604', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:55.211915', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:55.854066', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:56.365590', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:56.747963', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:56.749001', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:58.283859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:58.284477', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:59.691877', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:59.692494', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:01.227597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:01.227987', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:01.997559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:02.763812', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:07.243908', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:08.779979', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:10.187853', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:14.008218', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:14.511979', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:15.971633', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:18.382158', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:19.405591', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:28.109596', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:28.111259', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:28.235749', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:29.645485', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:29.772315', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:31.179873', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:32.715854', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:34.251734', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:35.787622', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:37.323848', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:38.731604', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:40.267597', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:42.872206', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:42.964102', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:43.885324', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:42:44.747869', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:46.283840', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:47.819817', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:48.078193', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:16.238143', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:32.109463', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:32.110237', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:32.111360', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:41.326059', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:44.397656', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:43:46.446358', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:18.213724', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:19.712938', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:19.913786', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:20.433212', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:23.321614', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:24.413057', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:27.240963', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:27.413234', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:30.209097', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:31.912956', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:37.682034', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:39.241725', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:43.902146', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:46.913533', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:48.413294', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:51.137435', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:35.788498', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:35.789482', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:47.819946', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:50.637622', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
