('2015-02-07 10:15:21.346213', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:21:18.274960', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:34:08.323040', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:55:07.330955', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:57:59.234932', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:05:14.306958', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:05:45.282823', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:15:07.203419', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:15:08.226869', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:15:35.234862', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:16:00.194914', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:16:01.218861', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:23:51.234934', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:24:03.266889', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:24:24.259054', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:24:25.282809', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:28:45.250914', 'Traceback (most recent call last):\n  File "/river/fd/fd_udp/fd_channel.py", line 187, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 819, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
