('2014-12-20 10:35:01.255886', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:03.274645', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:05.322695', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:07.242666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:09.290660', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:11.210667', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:13.258676', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:15.306648', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:17.226666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:19.274705', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:21.194689', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:23.242671', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:37.322654', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:35:39.242680', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:15.210659', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:17.258559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:19.306616', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:25.194765', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:27.242667', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:51.306672', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:36:53.226610', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:23.306693', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:25.226750', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:27.274666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:29.194641', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:31.242691', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:33.290533', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:39.178627', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:41.226623', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:37:45.783699', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:38:05.290797', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:05.291409', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:07.338682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:07.339013', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:11.178601', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:13.226780', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:15.274653', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:15.274947', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:19.242646', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:37.290653', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:37.291097', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:39.338699', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:41.258668', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:43.178724', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:45.226674', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:38:52.708240', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:39:19.274578', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:21.322772', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:21.323174', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:23.242669', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:23.242960', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:26.431349', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:39:26.439114', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:39:27.210635', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:27.394943', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:39:29.258667', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:31.306615', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:31.306866', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:35.274729', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:53.322652', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:55.242625', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:55.243075', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:57.290695', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:39:59.210695', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:21.692424', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2014-12-20 10:40:37.226667', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:37.227032', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:39.274696', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:43.242673', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:45.290674', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:45.291182', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:47.338649', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:40:51.178666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:41:11.274681', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2014-12-20 10:41:20.130853', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 143, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2014-12-20 11:29:42.434403', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 203, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
