('2015-04-18 10:35:17.787810', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:19.322899', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:20.730948', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:20.731495', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:23.674759', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:35:59.770928', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:01.307013', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:20.763094', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:22.298745', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:23.834861', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 10:36:25.243025', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:22.959188', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:23.524318', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:24.031211', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:25.516236', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:28.092512', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:31.532190', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:31.708409', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:34.912603', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:36.820783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:40.708850', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:43.637018', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:44.843783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:45.116453', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:51.548488', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:52.282812', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:52.668534', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:52.843810', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:53.563753', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:55.228175', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:55.548209', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:29:56.762855', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:58.171911', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:58.173193', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:29:59.706840', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:01.242962', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:04.315044', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:04.315655', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:05.722815', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:07.259019', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:08.794816', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:11.738767', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:13.052410', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:30:13.274788', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:14.810884', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:16.060419', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:30:16.218737', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:16.219032', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:23.467706', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:30:26.714814', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:26.715164', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:28.251000', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:29.787062', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:29.787559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:31.195080', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:32.730966', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:34.266799', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:34.267277', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:40.283145', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:41.690783', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:43.226780', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:43.227262', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:44.762901', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:44.763508', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:44.891807', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-04-18 11:30:46.299287', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:49.243001', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:50.778981', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:52.186994', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:53.722756', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:58.330815', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:59.738901', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:30:59.739415', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:31:01.274832', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-04-18 11:31:01.275297', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 235, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
