('2015-02-07 10:33:47.639046', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:48.677546', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:56.549286', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:06.085302', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:07.109824', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:08.837368', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:11.845958', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:54.115031', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:54.115544', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:54.115892', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:04.325122', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:07.267757', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:34.275736', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:35.683654', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:37.219878', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:54.117730', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:58.211684', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:04.227670', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:05.763632', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:07.171652', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:13.315869', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:20.739614', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:22.275665', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:23.811776', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:25.219673', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:28.291685', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:29.699741', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:31.235633', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:32.771680', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:34.307809', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:35.715732', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:44.803890', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:58.351752', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:36:59.779679', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:01.187887', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:07.332067', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:11.684437', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:13.219647', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:14.755732', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:16.291742', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:17.827611', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:19.235802', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:20.771663', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:22.179779', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:22.180119', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:23.715642', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:23.716121', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:25.251887', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:25.252346', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:26.787657', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:26.788086', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:27.789337', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:28.323713', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:28.726394', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:28.754131', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:29.731600', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:30.656677', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:31.267682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:32.675635', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:34.211610', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.747684', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.747974', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.283725', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:38.819726', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.227654', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.228113', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:47.779748', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:49.315747', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:50.723723', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:50.724265', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:52.259594', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:53.795748', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:55.203670', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:56.739727', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:04.291761', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:10.307807', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:11.715701', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:13.251714', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:19.267735', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:19.268066', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:20.803903', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:20.804518', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:22.211740', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:22.212109', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:23.747677', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:23.747958', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:25.283627', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:26.691659', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:28.227655', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:28.228129', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:29.763669', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:31.299675', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:37.445279', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:38:50.755859', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.291633', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.292235', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:53.828223', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:55.235605', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:56.771620', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:58.179679', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:04.323932', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:05.731701', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:14.819782', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:16.227916', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:17.763649', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:18.416370', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:19.171598', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:20.707676', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:20.854952', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:21.989256', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:26.723698', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:26.724165', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:28.259656', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:28.260092', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:29.795718', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:31.203653', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:31.204989', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:32.739875', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:32.741072', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:34.275917', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:40.291956', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:41.699559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:43.235620', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:44.771674', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:48.101675', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:48.613449', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:48.614443', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:52.195665', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:01.413091', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:40:01.413548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:40:22.405560', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:18.688666', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:21.006485', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:21.193025', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:23.241368', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:24.928908', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:26.769135', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:27.208582', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:28.712562', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:30.209134', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:31.708605', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:33.209274', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:36.208670', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:37.808729', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:39.007890', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:46.709177', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:48.120604', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:49.625170', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:50.430085', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:56.429720', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:57.329885', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:57.821035', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:05.827907', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:13.941672', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:23.747691', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:29.763593', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:38.723692', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:40.259806', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:41.667749', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:43.203731', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:44.739981', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:48.261291', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:53.699822', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:58.307909', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:59.715672', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
