('2015-02-07 10:33:46.591477', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:49.058780', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:50.595074', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:33:53.186956', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:08.866560', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:36.675210', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:54.154186', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:34:54.154903', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:01.346569', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:13.313796', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:14.721553', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:17.793503', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:44.801561', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:35:54.146974', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:35:54.147652', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:36:08.737525', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:10.273613', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:14.753533', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:19.233518', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:20.769513', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:22.177761', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:38.817595', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:40.225518', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:41.761565', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:43.169592', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:44.705581', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:46.241579', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:47.777546', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:36:48.362028', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:01.217684', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:08.769562', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:10.305472', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:11.713524', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:13.249909', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:14.785501', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:16.193799', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:16.194234', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:17.729504', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:19.265568', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:20.801566', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:22.337671', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:23.745569', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:25.219625', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:25.281531', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:28.485003', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:32.833854', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:34.241546', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:34.242011', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.777582', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:35.778018', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.185595', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.185913', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:37.432491', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:37:38.721639', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:38.721932', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.257614', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:40.258034', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:41.793558', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:43.332266', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:44.737499', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:46.273542', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:49.217684', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:50.753501', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:37:52.289656', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:01.249586', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:02.785682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:04.321730', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:05.729557', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:05.729912', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:07.265784', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:07.266340', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:08.673864', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:08.674329', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:10.209602', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:11.745560', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:13.281588', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:17.761843', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:17.762476', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:19.169591', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:20.705662', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:32.737539', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:34.273801', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:35.809548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:37.217532', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:37.217839', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:38.753621', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:38.753926', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:40.289576', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:40.290086', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:41.697548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:43.233593', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:44.769596', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:46.305976', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:47.713573', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:49.249607', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:50.785765', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.193535', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:52.771339', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:38:53.729498', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:55.265545', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:56.801579', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:58.337710', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:38:59.745715', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:01.155325', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:39:05.706641', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:08.833536', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:10.241792', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:10.242809', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:11.777566', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:11.777872', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:12.801941', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:39:13.185577', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:13.185950', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:14.721527', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:14.721847', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:16.257556', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:16.258015', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:17.793705', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:19.329635', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:19.330393', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:20.737554', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:20.737987', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:22.273548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:22.274005', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:23.681602', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:23.682094', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:25.217757', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:28.289762', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:31.233542', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:34.177682', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:35.713862', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:37.249811', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:38.785581', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:40.321603', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:41.729581', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:43.265586', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:44.673610', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:46.209768', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:39:47.745687', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:10.273850', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:11.809655', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:13.217561', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:14.753567', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:16.289527', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:17.697553', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:17.697900', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:19.233569', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:19.233926', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:20.769559', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:20.769860', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:22.305553', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:22.306133', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:23.713661', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:23.714153', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:25.251548', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:25.252427', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:26.785775', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:26.786639', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:28.193574', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:29.729588', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:31.265552', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:31.265863', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:32.801777', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:32.802107', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:34.337575', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:34.337911', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:35.745540', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:38.689498', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:43.297556', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:44.833610', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:45.126486', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:40:46.241760', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:47.777541', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:49.185889', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:52.257771', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:53.793553', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:55.329770', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:56.737540', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:58.273576', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:58.274037', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:40:59.681549', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:07.233846', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:13.190228', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:13.292670', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status\n    raise BadStatusLine(line)\nhttp.client.BadStatusLine: \'\'\n')
('2015-02-07 10:41:22.209724', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:23.745621', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:25.281736', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:26.817656', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:31.169538', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:31.682367', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:31.683015', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:31.683770', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:32.705584', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:32.705954', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:34.241874', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:34.242414', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:35.777605', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:35.777941', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:40.257567', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:40.898494', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:41:41.793903', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:41:43.201565', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 10:42:01.890364', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:01.890805', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:32.611668', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 10:42:38.243145', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 144, in pyget\n    ack  = handle.getresponse()\n  File "/usr/lib/python3.4/http/client.py", line 1147, in getresponse\n    response.begin()\n  File "/usr/lib/python3.4/http/client.py", line 351, in begin\n    version, status, reason = self._read_status()\n  File "/usr/lib/python3.4/http/client.py", line 313, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")\n  File "/usr/lib/python3.4/socket.py", line 371, in readinto\n    return self._sock.recv_into(b)\n  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into\n    return self.read(nbytes, buffer)\n  File "/usr/lib/python3.4/ssl.py", line 618, in read\n    v = self._sslobj.read(len, buffer)\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:19.727263', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:19.915745', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:21.207925', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:23.363354', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:27.347211', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:29.344371', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:31.614707', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:31.823691', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:33.091406', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:34.915873', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:39.254443', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:40.847470', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:42.135689', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:43.923117', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:45.015738', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:46.004955', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:51.751243', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:29:57.475194', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:02.178944', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:34.658869', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:35.681474', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:38.753678', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:44.769508', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:45.091208', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
('2015-02-07 11:30:49.249554', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:50.785752', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:52.321555', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:52.321903', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1197, in connect\n    self.timeout, self.source_address)\n  File "/usr/lib/python3.4/socket.py", line 509, in create_connection\n    raise err\n  File "/usr/lib/python3.4/socket.py", line 500, in create_connection\n    sock.connect(sa)\nTimeoutError: [Errno 110] Connection timed out\n')
('2015-02-07 11:30:52.323740', 'Traceback (most recent call last):\n  File "/river/fd/fd_worker/fd_channel.py", line 204, in create_channel\n    handle.connect()\n  File "/usr/lib/python3.4/http/client.py", line 1205, in connect\n    server_hostname=server_hostname)\n  File "/usr/lib/python3.4/ssl.py", line 364, in wrap_socket\n    _context=self)\n  File "/usr/lib/python3.4/ssl.py", line 578, in __init__\n    self.do_handshake()\n  File "/usr/lib/python3.4/ssl.py", line 805, in do_handshake\n    self._sslobj.do_handshake()\nConnectionResetError: [Errno 104] Connection reset by peer\n')
